### ISSUE TITLE
Installation of jdee-live does not correctly copy .clj file

### ISSUE THREAD

**Issue by dakrone** [phillord/jde-with-clojure-backend#1]
It looks like starting the `jdee-live-jack-in` looks for a `.clj` file that isn't copied/installed when starting up:

```
Starting nREPL server via mvn jdee:jdee-maven-nrepl:java -Dexec.mainClass="clojure.main" -Dexec.args="/home/hinmanm/.emacs.d/elpa/jdee-live-0.1snapshot/jdee-launch-nrepl.clj" -Dexec.includePluginsDependencies=true...
checking [INFO] Scanning for projects...

checking Downloading: https://repo.maven.apache.org/maven2/jdee/jdee-maven-nrepl/maven-metadata.xml

checking 
checking [INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building jdee-sample 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------

checking [INFO] 
[INFO] --- jdee-maven-nrepl:0.1-SNAPSHOT:java (default-cli) @ jdee-sample ---

checking [WARNING] 

checking java.lang.reflect.InvocationTargetException
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:293)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.FileNotFoundException: /home/hinmanm/.emacs.d/elpa/jdee-live-0.1snapshot/jdee-launch-nrepl.clj (No such file or directory)
    at java.io.FileInputStream.open0(Native Method)
    at java.io.FileInputStream.open(FileInputStream.java:195)
    at java.io.FileInputStream.<init>(FileInputStream.java:138)
    at java.io.FileInputStream.<init>(FileInputStream.java:93)
    at clojure.lang.Compiler.loadFile(Compiler.java:7162)
    at clojure.main$load_script.invoke(main.clj:275)
    at clojure.main$script_opt.invoke(main.clj:337)
    at clojure.main$main.doInvoke(main.clj:421)
    at clojure.lang.RestFn.invoke(RestFn.java:408)
    at clojure.lang.Var.invoke(Var.java:379)
    at clojure.lang.AFn.applyToHelper(AFn.java:154)
    at clojure.lang.Var.applyTo(Var.java:700)
    at clojure.main.main(main.java:37)
    ... 6 more
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.171 s
[INFO] Finished at: 2015-08-25T12:13:19-06:00
```

**Comment by dakrone** [comment]
(It works great if I manually copy the `jdee-launch-nrepl.clj` file into that directory)

**Comment by phillord** [comment]
Oh, yeah. Sorry. I haven't been using the cask generated package -- naughty me! Easy to fix.
